<a href="https://colab.research.google.com/github/abel-wosula/Python/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy for Data Analysis**
Once NumPy is installed, import it in your applications by adding the import keyword:

import numpy



In [ ]:
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


NumPy is usually imported under the np alias

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Numpy version - Version string is stored under __version__ attribute.

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


**Create a NumPy ndarray Object**

NumPy is used to work with arrays. The array object in NumPy is called ndarray (N-dimensional array).

We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Dimensions in Arrays**

A dimension in arrays is one level of array depth (nested arrays)

Nested array - are arrays that have arrays as their elements.

In [ ]:
# 0 D Array

import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [ ]:
# 1D array / uni-dimensional array

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)


[1 2 3 4 5]


In [ ]:
# 2D Array
#  often used to represent matrix or 2nd order tensors.

import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

print(arr)



[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.

import numpy as np

arr = np.array([[[1,2,3], [4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**How to check the number of dimensions**

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[6,7,8], [9,10,11]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimension Arrays**

In [ ]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


**NumPy Array Indexing**

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[2] + arr[3])

7


**Accessing elements on2D Arrays**


To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [3]:
# Access the element on the first row, second column

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print('2nd  element in the first row, second column in the 2D array is: ', arr[0, 1])
print('element on the second row, fifth column is: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd  element in the first row, second column in the 2D array is:  2
element on the second row, fifth column is:  10


**Accessing elements in 3D Arrays**

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [6]:
import numpy as np

arr = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

print(arr)
print('the third element of the second array of the first array: ', arr[0,1,2])


[[[1 2 3]
  [3 4 5]
  [6 7 8]]]
the third element of the second array of the first array:  5


**Negative Indexing**

Use negative indexing to access an array from the end.

In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('last element from 2nd dim: ', arr[1, -1])

last element from 2nd dim:  10
